/**:
  ros__parameters:

    topics:
      odom_topic: /orca/odom #Odometry
      twist_topic: /dvl/twist #Twist
      pose_topic: /dvl/pose #Pose
      guidance_topic: /guidance/los #Guidance
      thrust_topic: /orca/wrench_input #Thrust
      softwareoperation_topic: /softwareOperationMode #Software Operation
      killswitch_topic: /softwareKillSwitch #Kill Switch

    LQR_params:
      Q: [300.0,32.84,32.84,32.84,32.84,100.0,32.84,32.84]
      R: [0.02,3.1,3.10]
    NMPC_params:
      Q: [1.0,0.0,0.0,0.0,0.1,0.1,0.0,2.0,5.0] # u,v,w,p,q,r,phi,theta,psi
      R: [0.1,1.0,1.0] # u_surge, u_theta, u_psi
      N: 20
    inertia_matrix: [ 30.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 30.0, 0.0, 0.0, -0.6, 0.3, 0.0, 0.0, 30.0, 0.6, 0.3, 0.0, 0.0, 0.0, 0.6, 0.68, 0.0, 0.0, 0.0, -0.6, 0.3, 0.0, 3.32, 0.0, 0.6, 0.3, 0.0, 0.0, 0.0, 3.34]
    dampening_matrix_low:  [23.0,0.0,0.0,0.0,0.0,0.0, 0.0,46.0,0.0,0.0,0.0,0.0,  0.0,0.0,46.0,0.0,0.0,0.0,  0.0,0.0,0.0,46.0,0.0,0.0,  0.0,0.0,0.0,0.0,46.0,0.0, 0.0,0.0,0.0,0.0,0.0,46.0]
    dampening_matrix_high: [1.0,0.0,0.0,0.0,0.0,0.0, 0.0,1.0,0.0,0.0,0.0,0.0,  0.0,0.0,1.0,0.0,0.0,0.0,  0.0,0.0,0.0,1.0,0.0,0.0,  0.0,0.0,0.0,0.0,1.0,0.0, 0.0,0.0,0.0,0.0,0.0,1.0]

    #calculation_rate: 200 #ms integer
    publish_rate: 100 #ms
    #Clamp parameter
    max_force: 99.5 #should maybe be 99.5
    controller_type: 4 #1 PID 2 LQR 3 NMPC 4NMPC fast
    
    #Q: [300.0,0.01,0.01,0.01,32.84,32.84,32.84,32.84,32.84] # u,v,w,p,q,r,phi,theta,psi
    # R: [0.02,3.1,3.10] # u_surge, u_theta, u_psi
