/**:
  ros__parameters:
    pose_message_type: "PoseStamped"
    pose_sub_topic: "pose"
    pose_array_pub_topic: "filtered_pose_array"
    target_frame: "odom"
    update_interval_ms: 100

    # IPDA config
    ipda:
      prob_of_survival: 0.99
      prob_of_detection: 0.7
      mahalanobis_gate_threshold: 2.5 # in std deviations
      min_gate_threshold: 1.0 # in meters
      max_gate_threshold: 10.0 # in meters
      clutter_intensity: 0.001

    # Dyn model config
    dyn_mod:
      std_pos: 0.2
      std_orient: 0.2

    # Sensor model config
    sensor_mod:
      std_pos: 0.1
      std_orient: 0.1
      max_angle_gate_threshold: 0.4 # in radians

    # Existence management config
    existence:
      confirmation_threshold: 0.6
      deletion_threshold: 0.2
      initial_existence_probability: 0.4
