/**:
  ros__parameters:
    # Kp: [70.0, 70.0, 70.0, 12.0, 12.0, 12.0]
    # Ki: [2.0, 2.0, 2.0, 0.12, 0.12, 0.12]
    # Kd: [10.0, 10.0, 10.0, 4.0, 5.0, 4.0]
    Kp_x: 20.0
    Kp_y: 0.0
    Kp_z: 50.0
    Kp_roll: 0.0
    Kp_pitch: 0.0
    Kp_yaw: 0.0
    Ki_x: 0.08
    Ki_y: 0.0
    Ki_z: 0.0
    Ki_roll: 0.0
    Ki_pitch: 0.0
    Ki_yaw: 0.0
    Kd_x: 0.0
    Kd_y: 0.0
    Kd_z: 0.0
    Kd_roll: 0.0
    Kd_pitch: 0.0
    Kd_yaw: 0.0
