adaptive_los:
  lookahead_distance_h: 1.5
  lookahead_distance_v: 0.6
  gamma_h: 0.05
  gamma_v: 0.1

prop_los:
  lookahead_distance_h: 1.5
  lookahead_distance_v: 0.6
  k_p_h: 0.5
  k_p_v: 0.5

integer_los:
  lookahead_distance_h: 1.5
  lookahead_distance_v: 0.6
  k_p_h: 0.5
  k_p_v: 0.5
  k_i_h: 0.1
  k_i_v: 0.1

vector_field_los:
  max_approach_angle_h: 1.0   # rad
  max_approach_angle_v: 0.6   # rad
  k_p_h: 0.5
  k_p_v: 0.5

common:
  active_los_method: 2  # 0: Proportional, 1: Integral, 2: Adaptive
  u_desired: 0.3
  goal_reached_tol: 1.0

debug:
  enable_debug: false
  debug_topic_name: /los_guidance_debug