eskf_node:
  ros__parameters:
    imu_topic: /imu/data_raw
    dvl_topic: /orca/twist
    odom_topic: odom_ESKF
    diag_Q_std: [0.05, 0.05, 0.1, 0.01, 0.01, 0.02, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001]
    diag_p_init: [1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.1, 0.1, 0.1, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    imu_frame_r: [ -1.0,  0.0,  0.0,
                0.0, 1.0,  0.0,
                0.0,  0.0, -1.0 ]
    imu_frame_t: [ 0.0, 0.0, 0.0 ]

    dvl_frame_r: [ 1.0,  0.0,  0.0,
                  0.0,  1.0,  0.0,
                  0.0,  0.0, 1.0 ]

    dvl_frame_t: [ 0.0, 0.0, 0.0 ]

    depth_frame_t: [ 0.0, 0.0, 0.0 ]
    use_tf_transforms: false
