# This file defines parameters specific to Gladlaks
#
# When looking at the AUV from above, the thruster placement is:   
#
#        front
#       |======|
#  |=7↗=|      |=0↖=|
#  |    |      |    |
#  | 6• |      | 1• |
#  |    |      |    |
#  |    |      |    |
#  | 5• |      | 2• |
#  |    |      |    |
#  |=4↖=|==||==|=3↗=|
#

physical:
  mass_kg: 0
  displacement_m3: 0
  center_of_mass: [0, 0, 0]
  center_of_buoyancy: [0, 0, 0]

propulsion:
  dofs:
    num: 6
    which:
      surge: true
      sway:  true
      heave: true
      roll:  true
      pitch: true
      yaw:   true
  thrusters:
    num: 8
    configuration_matrix:
      [[ 0.70711,  0.00000,  0.00000,  0.70711,  0.70711,  0.00000,  0.00000, 0.70711], # Surge
       [ 0.70711,  0.00000,  0.00000,  -0.70711, 0.70711,  0.00000,  0.00000,-0.70711], # Sway
       [ 0.00000,  1.00000,  1.00000,  0.00000,  0.00000,  1.00000,  1.00000, 0.00000], # Heave
       [ 0.00000, -0.22000, -0.22000,  0.00000,  0.00000,  0.22000,  0.22000, 0.00000], # Roll
       [ 0.06500, -0.24000,  0.24000,  0.06500,  0.06500,  0.24000, -0.24000, 0.06500], # Pitch 
       [ 0.32557,  0.00000,  0.00000,  0.32557,  -0.32557, 0.00000,  0.00000,-0.32557]] # Yaw

    rate_of_change:
      max: 1 # Maximum rate of change in newton per second for a thruster
    characteristics:  
      thrust:      [-34.5, -24.0, -12.9, -3.92, 0.00, 4.91, 12.6, 26.1, 35.5, 44.3] 
      pulse_width: [ 1100,  1192,  1292,  1400, 1500, 1600, 1676, 1780, 1840, 1900]

controllers:
  dp:
    circleOfAcceptance: 0.10
    frequency: 40 # THIS SHOULD BE 40Hz for the controller to perform good. This is because the built in reference model will work 2x faster as if the controller ran at 20Hz
    velocity_gain: 3.5   #0.4
    position_gain: 30.5   #5.0
    attitude_gain: 1.3  #2.5
    integral_gain: 0.024 #0.3
  los_controller: # Note: Not loaded by the backstepping/pid controllers yet! Make sure to do this after tuning with dyn. reconf.
    PID:
      p: 25.0
      i: 0.0024
      d: 3.5
      sat: 3.0
    backstepping:
      c:  3.75
      k1: 45.0
      k2: 28.0
      k3: 10.5
      
guidance:
  LOS:
    delta: 0.7
        
joystick:
  scaling:
    surge: 10
    sway: 10
    heave: 10
    roll: 5
    pitch: 5
    yaw: 5

battery:
  thresholds:
    warning: 15000  # Millivolts
    critical: 14000 # Millivolts
  logging:
    frequency: 10   # Seconds
    path: "/sys/bus/i2c/drivers/ina3221x/1-0040/iio:device0/in_voltage0_input" # Path to monitor