name: Run Pre-Commit Workflow
# Run pre-commit hooks on a repository
on:
  workflow_dispatch:
  pull_request:
jobs:
  call_reusable_workflow:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-pre-commit.yaml@main
    with:
      ref: ${{ github.ref }}
      python_version: '3.11'
