name: ROS Node Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Runs daily at 01:00 UTC
jobs:
  ros-node-test:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-ros2-simulator-test.yml@main
    with:
      vcs_repos_file: "tests/dependencies.repos"
      setup_script: "tests/setup.sh"
      test_scripts: '[
        "tests/ros_node_tests/dp_node_test.sh",
        "tests/ros_node_tests/lqr_autopilot_node_test.sh",
        "tests/ros_node_tests/reference_filter_node_test.sh",
        "tests/ros_node_tests/los_node_test.sh",
        ]'
