name: Simulator Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Runs daily at 01:00 UTC
jobs:
  simulator-test:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-ros2-simulator-test.yml@main
    with:
      vcs_repos_file: "tests/dependencies.repos"
      setup_script: "tests/setup.sh"
      test_scripts: '[
        "tests/simulator_tests/waypoint_navigation/simulator_test.sh",
        "tests/simulator_tests/los_test/simulator_test.sh",
        "tests/simulator_tests/waypoint_manager_test/simulator_test.sh",
        ]'
